import os
import time
import argparse
import pandas as pd
import re
import sys

parser = argparse.ArgumentParser(description="Process LTR content output by HiTE to standardize intact LTR nomenclature")
parser.add_argument('--fa', type=str, required=True, help='Genomic sequence file (FASTA)')
parser.add_argument('--bed', type=str, required=True, help='Annotation file for intact LTRs (BED format)')
args = parser.parse_args()


def intactLTR_rename(bed, fa):
    """Renames intact LTR elements based on classification results."""
    prefix = bed.split('.')[0]
    intact_fa = f"{prefix}.intactLTR.fa"
    command_getfasta = f"bedtools getfasta -fi {fa} -bed {bed} -fo temp.fa -s -nameOnly"
    os.system(command_getfasta)
    print(f"***** Extracted sequences for {intact_fa} *****")
    clean_fasta_headers('temp.fa', intact_fa)
    os.remove('temp.fa')
    # Rename intact LTRs using TEsorter
    tesorter_rename(intact_fa, bed)

def clean_fasta_headers(input_file, output_file):
    """
    Reads a FASTA file, cleans sequence headers, and writes to a new FASTA file.
    Cleaning rule: Removes `(?)`, `(+)`, or `(-)` suffixes from the end of sequence headers.

    Args:
        input_file (str): Path to the input FASTA file.
        output_file (str): Path to the output cleaned FASTA file.
    """
    # This regex matches the following pattern at the end of a line:
    # \s*     - Zero or more whitespace characters
    # \(      - Literal opening parenthesis
    # [?+\-]  - A single character within the parentheses: '?', '+', or '-'
    # \)      - Literal closing parenthesis
    # $       - End of string anchor
    pattern_to_remove = re.compile(r'\s*\([?+\-]\)$')

    print(f"Starting processing for file: {input_file}")
    lines_processed = 0
    headers_cleaned = 0

    try:
        with open(input_file, 'r', encoding='utf-8') as f_in, \
             open(output_file, 'w', encoding='utf-8') as f_out:
            
            for line in f_in:
                lines_processed += 1
                # Check if the line is a header (starts with '>')
                if line.startswith('>'):
                    # Strip newline for processing
                    header = line.strip()
                    # Replace the matched pattern with an empty string
                    cleaned_header = pattern_to_remove.sub('', header)
                    
                    if header != cleaned_header:
                        headers_cleaned += 1
                    
                    # Write cleaned header back with a newline
                    f_out.write(cleaned_header + '\n')
                else:
                    # Directly write sequence lines
                    f_out.write(line)

    except FileNotFoundError:
        print(f"Error: Input file '{input_file}' not found.", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"An error occurred during processing: {e}", file=sys.stderr)
        sys.exit(1)

    print("\nProcessing complete!")
    print(f"Total lines processed: {lines_processed}.")
    print(f"Total headers cleaned: {headers_cleaned}.")
    print(f"Results saved to: {output_file}")

def tesorter_rename(input_fa, input_bed):
    """
    Takes a sequence file and its corresponding BED file, then replaces 
    the names in the BED file with annotations generated by TEsorter.
    """
    prefix = input_bed.rsplit('.', 1)[0]
    # Perform TEsorter annotation to generate the *.cls.tsv classification file
    command_tesorter = f"TEsorter {input_fa} -p 16 -pre {prefix} -db rexdb-plant"
    os.system(command_tesorter)
    
    # Convert *.cls.tsv to a mapping of ID to classification name (tsName)
    cls_tsv = f"{prefix}.cls.tsv"
    temp = pd.read_csv(cls_tsv, sep='\t')
    temp['tsName'] = temp['Order'] + '_' + temp['Superfamily'] + '_' + temp['Clade']
    id_tsName = temp.loc[:, ['#TE', 'tsName']]
    id_tsName.columns = ['ID', 'tsName']
    id_tsName_map = f"{prefix}.tesorterLTR.txt"
    id_tsName.to_csv(id_tsName_map, index=False, sep='\t')
    
    # Execute conversion function
    id_tsName_bed = f"{prefix}.tesorterLTR.bed"
    ID_tsName_convert(input_bed, id_tsName_map, id_tsName_bed)
    print('-'*60)

def ID_tsName_convert(bed_path, map_path, output_path):
    """
    Uses pandas to process a BED file, replacing and reordering ID columns 
    based on a provided mapping file.

    Args:
        bed_path (str): Path to the input BED file.
        map_path (str): Path to the ID-to-tsName mapping file.
        output_path (str): Path to the output modified BED file.
    """
    try:
        # 1. Read BED file into a DataFrame with specified column names
        print(f"Reading BED file: {bed_path}")
        bed_columns = ['chrom', 'start', 'end', 'id', 'score', 'strand', 'anno']
        bed_df = pd.read_csv(bed_path, sep='\t', header=None, names=bed_columns)
        
        # 2. Read mapping file into a DataFrame
        print(f"Reading mapping file: {map_path}")
        map_df = pd.read_csv(map_path, sep='\t')

    except FileNotFoundError as e:
        print(f"Error: File not found - {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error reading files: {e}", file=sys.stderr)
        sys.exit(1)

    print("File reading successful. Commencing data merge...")
    # 3. Merge DataFrames
    # Use a left join to retain all rows from the original BED file
    merged_df = pd.merge(bed_df, map_df, left_on='id', right_on='ID', how='left')

    # 4. Handle unmapped IDs
    # Count IDs that were not found in the mapping file
    unmapped_count = merged_df['tsName'].isnull().sum()
    if unmapped_count > 0:
        print(f"Warning: {unmapped_count} IDs could not be found in the mapping file.")
        # Fill missing tsNames with 'none' (or a placeholder for unknown classifications)
        merged_df['tsName'].fillna('none', inplace=True)

    # 5. Select and reorder final columns
    # New column order: chrom, start, end, tsName (classification), id (original ID), strand, anno
    final_df = merged_df[['chrom', 'start', 'end', 'tsName', 'id', 'strand', 'anno']]

    # 6. Write results to file
    print(f"Writing results to: {output_path}")
    try:
        final_df.to_csv(
            output_path, 
            sep='\t',        # Use tab as separator
            header=False,    # Do not write header
            index=False      # Do not write row indices
        )
    except Exception as e:
        print(f"Error writing to file: {e}", file=sys.stderr)
        sys.exit(1)

    print("\nProcessing complete!")
    print(f"Successfully processed {len(bed_df)} rows of BED data.")
    print(f"Results saved to: {output_path}")


if __name__ == "__main__":
    intactLTR_rename(args.bed, args.fa)